// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmnkFMe9UA7CYDy6NcrCIMgXVP6kkjPcE',
    appId: '1:300316195291:web:d82b02497f091362510ffe',
    messagingSenderId: '300316195291',
    projectId: 'swiftcollect-jzh5n',
    authDomain: 'swiftcollect-jzh5n.firebaseapp.com',
    storageBucket: 'swiftcollect-jzh5n.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuR9qjq5BlsH0c_bQiHWh1GzjCmh_y5_M',
    appId: '1:300316195291:android:6b877d964adb14a2510ffe',
    messagingSenderId: '300316195291',
    projectId: 'swiftcollect-jzh5n',
    storageBucket: 'swiftcollect-jzh5n.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhSfmp-baVjMVtyuGruYfLdr0PqDdmpmo',
    appId: '1:300316195291:ios:7267bc91abee775d510ffe',
    messagingSenderId: '300316195291',
    projectId: 'swiftcollect-jzh5n',
    storageBucket: 'swiftcollect-jzh5n.firebasestorage.app',
    iosBundleId: 'com.example.mulmetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhSfmp-baVjMVtyuGruYfLdr0PqDdmpmo',
    appId: '1:300316195291:ios:7267bc91abee775d510ffe',
    messagingSenderId: '300316195291',
    projectId: 'swiftcollect-jzh5n',
    storageBucket: 'swiftcollect-jzh5n.firebasestorage.app',
    iosBundleId: 'com.example.mulmetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmnkFMe9UA7CYDy6NcrCIMgXVP6kkjPcE',
    appId: '1:300316195291:web:60f2a0e3965a6bc4510ffe',
    messagingSenderId: '300316195291',
    projectId: 'swiftcollect-jzh5n',
    authDomain: 'swiftcollect-jzh5n.firebaseapp.com',
    storageBucket: 'swiftcollect-jzh5n.firebasestorage.app',
  );
}
